### PR TITLE
Add 'email' to socials

### PR DESCRIPTION
**Pull request by omarroth**
[Vanilla-sharing](https://github.com/avdeev/vanilla-sharing#emailoptions) has an `email` option that doesn't appear to be supported by this plugin.

This is a first pass at adding support. It uses the same icon and colors as `mail`. `email.svg` is currently a copy of `mail.svg`, since I was unfortunately not able to make it work without having a second file with the name of the social. 

Also may make sense to add `subject` to `socialOptions()`, although I'm not sure how that should be handled.

### CODE REVIEW

**Comment by avdeev** [comment]
@omarroth Thanks! I think we can add a `subject` upon user request.

**Comment by avdeev** [comment]
@omarroth Could you test this in the master branch? And I'll publish a release in NPM.

**Comment by omarroth** [comment]
Built from master, appears to work as expected :+1:

**Comment by avdeev** [comment]
@omarroth I've published v3.2.0 to NPM. You can switch to registry.

**Pull request merged**
