### PR TITLE
Optional Embed Input

### PR DESCRIPTION
**Pull request by arl1nd**
Make embedContainer optional, if there is no markup do not display the field

### CODE REVIEW

**Comment by avdeev** [comment]
@arl1nd Thanks!
Could you add this option to README?

**Comment by arl1nd** [comment]
Sure, just a minute. Thanks for prompt reply.

**Comment by avdeev** [comment]
@arl1nd I released it! You can upgrade version to 3.0.0.

**Comment by arl1nd** [comment]
@avdeev thanks a lot! I really appreciate your consideration to add this patch. 

Have a great weekend!

**Pull request merged**
